### ISSUE TITLE
Remember which space I am using

### ISSUE THREAD

**Issue by floelhoeffel** [contentful/create-contentful-extension#12]
I think it would be great to remember my last used space. When I switch between develop, build and deploy I dont want to re-choose my space all the time.

**Comment by svandersteene** [comment]
You can add a .env file with your space-id (and your management token) in your project directory, source it and then create a new script, for example like this:

![Screenshot 2019-03-13 at 09 12 18](https://user-images.githubusercontent.com/33860193/54263052-291e0e00-4570-11e9-90b4-89f4ea943869.png)

And a .env file like this:
![Screenshot 2019-03-13 at 09 14 00](https://user-images.githubusercontent.com/33860193/54263128-61bde780-4570-11e9-917b-f63e23954f10.png)

**Comment by suevalov** [comment]
@svandersteene Thanks for your comment. I'll add this information to `README.md` and close the issue.

**Comment by suevalov** [comment]
@floelhoeffel I've add FAQ section that answers the question.
