### ISSUE TITLE
Possibility to specify build directory

### ISSUE THREAD

**Issue by svandersteene** [contentful/create-contentful-extension#15]
Is it possible to create a build-script in which you can specify which folder it has to build?

My script now:
`"build": "contentful-extension-scripts build"`

But then I get a Parcel-error: No entries found.

My project-structure e.g. :
```
root
   node_modules/
   package.json
   extensions/
      barcode-checker/
         src/
            index.js
            index.html
            index.css
         extension.json
```

**Comment by suevalov** [comment]
@svandersteene Right now there's no way to specify build folder. We could potentially add possibility to override build folder using `.env` vars but I'm not sure about benefits.

If I understood correctly from your example you want to have one `package.json` for all extensions in your folder. I'd suggest consider each extension as mini-app and keep `package.json` and `node_modules` separate.

**Comment by svandersteene** [comment]
@suevalov thanks for your answer.

At the moment, I hot-fixed it by adding `cd xx/xx` to my project folder, this because I'm creating my extension inside a bigger project.

I'm planning to write a shell-script to fix this issue, I'll let you know if I have a solution.
