### ISSUE TITLE
No content from my UI extension in app.contentful.com

### ISSUE THREAD

**Issue by svandersteene** [contentful/create-contentful-extension#17]
Just a tip:

After a long search what might have been the problem of receiving no content at all in my custom UI extension;

The mixed content error can be solved by simply running over https (in scripts):
`"start": "HTTPS=true contentful-extension-scripts start"`

The other problem I had: I didn't receive any content from my dev-UI-extension, I fixed it by changing my index.html like this;
<img width="641" alt="image" src="https://user-images.githubusercontent.com/33860193/54353634-d23e3480-4654-11e9-9a02-e5be3425ef20.png">

Rule 5 & 6 were not included in the `$ npx @contentful/create-contentful-extension` and this fixed my problem of no content.

**Comment by suevalov** [comment]
@svandersteene What do mean by 'didn't receive any content from my dev-UI-extension'? Can you provide more details?

**Comment by svandersteene** [comment]
@suevalov I tried creating an extension served from localhost, but I didn't get the content of my Component (as created per $ npx @contentful/create-contentful-extension) in the webapp of Contentful.

The first problem was "mixed content" 'cause I was serving my localhost over HTTP instead of HTTPS, so that was an easy fix.

But then I still didn't get the content from my Component, it was just blank in the webapp. I got this second problem fixed by simply adding line 5 & 6 (screenshot first post) in my index.html. These lines are not included in the "create-contentful-extension".

I don't know if this was a user-specific problem, but that's why I made this issue, so you could, if necessary, fix this.

**Comment by suevalov** [comment]
@svandersteene Interesting, I'll take a look

**Comment by suevalov** [comment]
@svandersteene I investigated the problem and see no correlation between meta tags that we've added to `index.html` and extension that is not rendered.

If you `HTTPS=true` and extension is being served from `https://localhost:1234` then you need to open `https://localhost:1234` in your browser and proceed with unsafe mode. If you don't want to unable unsafe mode, then you need to install SSL certificate that is generated by `create-contentful-extension` (it's located in `.cache` folder at the root the extension after you run `npm run start`)

But in general I see no problem using cli without `HTTPS=true` and enable `mixed-content` for your current development session. It is automatically turned off after you close your browser.

P.S. What browser and OS are you using?

**Comment by suevalov** [comment]
@svandersteene I just verified scenario in Firefox 66 and could not reproduce the issue. Can you try to reproduce on your side?

**Comment by svandersteene** [comment]
@suevalov I just tried it and it worked. I don't know what the problem was then.. I guess I must have made a mistake. Sorry for the inconvenience.

**Comment by l5s** [comment]
I have the same problem. My browser window is completely blank. I tried adding the meta tags, but they didn't help. Any thoughts?

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/3186494/67428917-b7498080-f5a4-11e9-96e2-a854ed7d4789.png">

**Comment by mohammedzakkriya** [comment]
I am facing the same problem, the page is blank. 

http://localhost:52563 - configured port 1234 could not be used.
🚨  /Users/apple/Documents/GitHub/my-first-extension/src/index.js: 'loose' mode configuration must be the same for both @babel/plugin-proposal-class-properties and @babel/plugin-proposal-private-methods
