### ISSUE TITLE
Line number missing from stack trace

### ISSUE THREAD

**Issue by floelhoeffel** [contentful/create-contentful-extension#20]
a UI Extension rendering in different locations is throwing an exception because 

```
state = {
    value: this.props.sdk.field.getValue()
  }
```

does not exist when the extension is render in the sidebar. In the stack trace, I would expect an error which links to the line where the problem occurs:

![image (1)](https://user-images.githubusercontent.com/6864947/54693632-441bef80-4b27-11e9-8fd7-518abbbfa7a2.png)

**Comment by suevalov** [comment]
@floelhoeffel Sourcemaps problem should be solved in `0.6.0` version.

**Comment by svandersteene** [comment]
@floelhoeffel For the sake of the state, you should consider using immutables in the state as well :)
