### ISSUE TITLE
Need to restart dev server in an unpredictable time.

### ISSUE THREAD

**Issue by danbru-WittGruppe** [contentful/create-contentful-extension#21]
I have to restart the dev server in an unpredictable way after i made changes.

So, for example:
+ edit a string
+ safe changes
+ server rebuilds
+ switch to browser and see the changes.

After a second change, nothing of the above is working. I have to restart the server by hand and reload the page.

In package.json scripts i only changed the space and env id, because i need to work in a different env.

**Comment by danbru-WittGruppe** [comment]
Ok, looks like it is predictable. It only will HMR once. After that i have to restart the server.

**Comment by suevalov** [comment]
@danbru-WittGruppe Most likely HRM itself doesn't work properly in your case. We'll add possibility to reload extension automatically without HMR soon without a need to restart the server.

**Comment by danbru-WittGruppe** [comment]
@suevalov alright. Sounds good. Is there something i can use as a workaround in the meantime?

**Comment by suevalov** [comment]
@danbru-WittGruppe Hard to tell at the moment. If you could share with me the code of extension then maybe I could find some workaround.

"possibility to reload extension automatically without HMR" should be implemented in our WebApp and it's expected in two weeks.

**Comment by suevalov** [comment]
@danbru-WittGruppe I've just shipped "possibility to reload extension automatically without HMR" in the Web App.

Comment to following lines:
```
if (module.hot) {
   module.hot.accept();
}
```
to disable HRM. After this change the whole `iframe` will be reloaded on every save of a file.
