### ISSUE TITLE
Allow overriding publicUrl

### ISSUE THREAD

**Issue by westmark** [contentful/create-contentful-extension#29]
Hi! We'll be creating several Contentful extensions which we plan to host ourselves. However, currently Parcel's `publicUrl` is set to `./` for all builds, which is effectively baring us from deploying multiple extensions in separate folders on the same domain(the CSS and JS files will always be assumed to exist at the domain root) 

We can always monkey-patch the paths in the build artefacts I suppose, although we would prefer a cleaner solution of course.

**Comment by suevalov** [comment]
Hi @westmark! Thanks for filing an issue 👍 

I released possibility to override `publicUrl` in [contentful-extension-scripts@0.8.0](https://github.com/contentful/create-contentful-extension/releases/tag/%40contentful%2Fcontentful-extension-scripts%400.8.0).

```
contentful-extension-scripts build --no-inline --public-url=<your-url>
```

**Comment by Daronspence** [comment]
@westmark any chance I can pick your brain about how you accomplished that? We're looking to do something similar, but I'm pretty new to this npm workflow stuff and running into some walls. 

You can email me at `me at daronspence . com` 🙏
