### ISSUE TITLE
Building extensions does not support tsconfig `extends` property

### ISSUE THREAD

**Issue by nib-bturner** [contentful/create-contentful-extension#426]
I am using the `contentful-extensions-scripts start` command but have found that it is using Parcel version 1.x. It is a known bug that Parcel version 1 does not support tsconfig `extends` see [this article](https://github.com/parcel-bundler/parcel/issues/2856). 

There is a workaround currently that is to copy the `compilerOptions` from the parent tsconfig to the child (aka the extensions I am building) but would rather raise this as an issue as there is no dialogue to identify that the extended compiler options are not working.

**Comment by shikaan** [comment]
Hello @nib-bturner, thanks for reaching out.

Unfortunately, this repository is not expected to get updates as all new development in Contentful's extensibility is currently happening in Apps. You can read more about Apps [here](https://www.contentful.com/developers/docs/extensibility/app-framework/).

Equivalent tooling to this one, but for apps, can be found [here](https://github.com/contentful/create-contentful-app).

Best,
