### ISSUE TITLE
Cannot find module on start

### ISSUE THREAD

**Issue by sami616** [contentful/create-contentful-extension#45]
Following your setup instructions, i'm running into an issue where when i run `npm run start` i get an error complaining that the following module couldn't be found: `\node_modules\@contentful\contentful-extension-scripts\lib\index.js`

Running 0.36.0 of the contentful cli & node v10.16.1

**Comment by jasondark93** [comment]
Add `"@contentful/contentful-extension-scripts": "^0.14.0"` to dependencies in your extension's package.json and re run `npm install`.

I noticed this was missing by comparing my package.json file from older extensions I had made before this broke with new extensions.

Seems like this dependency does not get added at build time when you generate the extension. Will make a pull request.

**Comment by suevalov** [comment]
Looks like `@contentful/contentful-extension-scripts` is not being added to `package.json` on Windows. It definitely works on Mac and Linux.
