### ISSUE TITLE
Npm audit got high vulnerabilities.

### ISSUE THREAD

**Issue by lc-stevenzhang** [contentful/create-contentful-extension#49]
<img width="593" alt="Screen Shot 2019-11-05 at 9 23 19 AM" src="https://user-images.githubusercontent.com/32248179/68155132-f23cb280-ffad-11e9-9d4b-769d7b08fb80.png">
The first one.

**Comment by suevalov** [comment]
@lc-stevenzhang It depends on a `parcel` and we're using the latest one, so it's not something we can fix.

**Comment by davilima6** [comment]
This was fixed in parcel-bundler@1.12.4. Since `create-contentful-extension` uses 1.12.3 I think this can be reopened.
