### ISSUE TITLE
Neither Javascript or Typescript sidebar project are working

### ISSUE THREAD

**Issue by GordonApplepie** [contentful/create-contentful-extension#57]
There seems to be a folder change from lib to src and in general changes that made the tool break.

**Comment by GordonApplepie** [comment]
ah no wait. there seems to be a package missing in the js-text section cannot find module \node_modules\@contentful\contentful-extension-scripts\src\index.js'

**Comment by GordonApplepie** [comment]
found the problem. there are missing the dependencies for "@contentful/contentful-extension-scripts" in the different package.json files. and after that you also would need to change inside the packages the folder to src.

can't be to hard to fix

**Comment by fredski02** [comment]
Did you find a solution @GordonApplepie ?

**Comment by Jwhiles** [comment]
I believe issue is fixed, so I'm closing this. Feel free to re-open if you think this is still a problem.
