### ISSUE TITLE
Issue with UI extension creation

### ISSUE THREAD

**Issue by paragopinath** [contentful/create-contentful-extension#66]
Hi There,

I'm trying to create a UI extension using create UI extension CLI which is not working. I'm getting the following error when I try to run the dev env

<img width="871" alt="Screenshot 2020-05-07 at 6 16 29 PM" src="https://user-images.githubusercontent.com/56590166/81296006-e16d1680-908e-11ea-9d9e-300de4665a10.png">

I'm imagining that this is something to do with how the SDK is getting initiated. Any help would be greatly appreciated!
```
Failed to load resource: the server responded with a status of 404 ()
api.contentful.com/spaces/xxxxx/ui_config:1 
```
Thanks!

**Comment by Jwhiles** [comment]
Sorry for the slow response, I'm closing this issue - as I assume that you have resolved it by now. Feel free to re-open if this is still a problem and we will look into it.
