### ISSUE TITLE
Version Mismatch of with @contentful/field-editor-reference causing TypeScript errors

### ISSUE THREAD

**Issue by matt-koevort** [contentful/create-contentful-extension#86]
The create-contentful-extension CLI seems to install `contentful-ui-extensions-sdk` v3.13.0 [(link)](https://github.com/contentful/create-contentful-extension/blob/master/packages/contentful-extension-scripts/scripts/utils/updatePackageJsonFile.js#L28).

The @contentful/field-editor-reference library installs (at least) v3.18.0 [(link)](https://github.com/contentful/field-editors/blob/master/packages/reference/package.json#L30).

When using the two in conjunction in TypeScript, there are typing errors with the `sdk` prop from the App. Since the two versions of the sdk library have different definitions for `BaseExtensionsSDK`.

I wouldn't know the implications, but it would be nice if the CLI could match the version of the field editor library, which is expected to be used in conjunction with it.

**Comment by Jwhiles** [comment]
Hi @matt-koevort - we have some work in progress that should resolve these dependency issues. Thanks for raising it.
